"""unique owner_name+currency on accounts

Revision ID: 1fa0bdb00a55
Revises: 75d87e6854e1
Create Date: 2026-09-11 00:12:46.006965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa0bdb00a55'
down_revision: Union[str, Sequence[str], None] = '75d87e6854e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_accounts_owner_currency', 'accounts', ['owner_name', 'currency'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_accounts_owner_currency', 'accounts', type_='unique')
    # ### end Alembic commands ###
