"""add user_id foreign key to Accounts.

Revision ID: b95342c95564
Revises: 9cdf10d944a2
Create Date: 2026-09-18 20:21:09.785669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95342c95564'
down_revision: Union[str, Sequence[str], None] = '9cdf10d944a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###
