"""add notes to accounts.

Revision ID: ddd01873df6d
Revises: bf3d9fdf2b6e
Create Date: 2026-09-07 20:24:28.215342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd01873df6d'
down_revision: Union[str, Sequence[str], None] = 'bf3d9fdf2b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('notes', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'notes')
    # ### end Alembic commands ###
